apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-deployment
  labels:
    app: weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: weather-app
        image: yourdockerhubusername/weather-app:latest  # replace with your Docker Hub image name
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
spec:
  type: LoadBalancer
  selector:
    app: weather-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
