apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-deployment
  labels:
    app: weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: weather-app
        image: yuvalbenar/kubernetesweather:latest  # Default to latest for initial testing
        ports:
        - containerPort: 5000  # Ensure port matches your application configuration
---
apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
spec:
  type: LoadBalancer
  selector:
    app: weather-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000  # Match the container port to ensure correct routing
