name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        IMAGE_NAME=yuvalbenar/kubernetesweather
        TAG=${{ github.run_number }}  # Use GitHub run number as tag
        docker build -t $IMAGE_NAME:$TAG .
        docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest
        docker push $IMAGE_NAME:$TAG
        docker push $IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures that deploy only runs after build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH for deployment
      run: |
        sudo apt-get install -y sshpass

    - name: Replace image tag in Kubernetes YAML
      run: |
        IMAGE_TAG=${{ github.run_number }}
        sed -i "s|yuvalbenar/kubernetesweather:latest|yuvalbenar/kubernetesweather:$IMAGE_TAG|g" kubernetes/weather-app.yaml

    - name: Copy Kubernetes manifest to remote VM
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null kubernetes/weather-app.yaml sela@34.140.118.235:/home/sela/

    - name: SSH into VM and apply Kubernetes manifests
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null sela@34.140.118.235 "kubectl apply -f /home/sela/weather-app.yaml"
