name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH for deployment
      run: |
        sudo apt-get install -y sshpass

    - name: Replace image tag in Kubernetes YAML
      run: |
        IMAGE_TAG=${{ github.run_number }}
        sed -i "s|yuvalbenar/kubernetesweather:latest|yuvalbenar/kubernetesweather:$IMAGE_TAG|g" kubernetes/weather-app.yaml

    - name: SSH into VM and apply Kubernetes manifests
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null sela@34.140.118.235 "kubectl apply -f kubernetes/weather-app.yaml"
